#!/usr/bin/env python3
"""Extract the guest copy-progress curve for the paper's representative figure.

Reads a run directory produced by usb-migration-demo.sh. The guest heartbeat
carries, once per second, the wall clock, /proc/uptime and the size of the
in-progress copy ("DEMO-HEARTBEAT n <epoch> uptime=U copied=B"), so the curve is
a real measurement inside the guest rather than a reconstruction.

Writes:
  paper/data/copy_progress.dat   "<seconds since COPY_START> <MiB copied>"
  paper/data/migration_point.dat "<seconds since COPY_START at the migration>"

Usage: extract-progress.py <run-dir> [--out-dir paper/data]
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HB = re.compile(r"DEMO-HEARTBEAT\s+\d+\s+([\d.]+)\s+uptime=[\d.]+\s+copied=(\d+)")
COPY_START = re.compile(r"DEMO-COPY: COPY_START\s+([\d.]+)")
COPY_DONE = re.compile(r"DEMO-COPY: COPY_DONE\s+([\d.]+)\s+rc=(-?\d+)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("run")
    ap.add_argument("--out-dir", default="paper/data")
    args = ap.parse_args()

    log = os.path.join(args.run, "guest-demo.log")
    text = open(log, errors="replace").read()
    start = COPY_START.search(text)
    if not start:
        print("no COPY_START in the guest log", file=sys.stderr)
        return 1
    t0 = float(start.group(1))
    done = COPY_DONE.search(text)

    pts = []
    for epoch, copied in HB.findall(text):
        pts.append((float(epoch) - t0, int(copied) / (1024 * 1024)))
    pts = [(t, m) for t, m in pts if t >= 0]
    pts.sort()
    if done:
        pts.append((float(done.group(1)) - t0, 128.0))
    if not pts:
        print("no heartbeat lines with copied= in the guest log", file=sys.stderr)
        return 1

    ep = os.path.join(args.run, "migration.epoch")
    mig = None
    if os.path.exists(ep) and open(ep).read().strip():
        mig = float(open(ep).read().strip()) - t0

    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "copy_progress.dat"), "w") as fh:
        for t, m in pts:
            fh.write(f"{t:.2f} {m:.1f}\n")
    if mig is not None:
        with open(os.path.join(args.out_dir, "migration_point.dat"), "w") as fh:
            fh.write(f"{mig:.3f}\n")

    # macros so the figure and its caption cannot disagree with the data file
    dur = (float(done.group(1)) - t0) if done else None
    xmax = max(t for t, _ in pts) + 2
    with open(os.path.join(args.out_dir, "progress_meta.tex"), "w") as fh:
        fh.write("% GENERATED by paper/extract-progress.py -- do not edit by hand.\n")
        fh.write(f"\\newcommand{{\\ProgressRun}}{{{os.path.basename(args.run.rstrip('/'))}}}\n")
        if mig is not None:
            fh.write(f"\\newcommand{{\\ProgressMigPoint}}{{{mig:.2f}}}\n")
        if dur is not None:
            fh.write(f"\\newcommand{{\\ProgressCopyDuration}}{{{dur:.1f}}}\n")
            fh.write(f"\\newcommand{{\\ProgressMigMiB}}{{{mig is not None and next((m for t, m in pts if t >= mig), 0):.0f}}}\n")
        fh.write(f"\\newcommand{{\\ProgressXMax}}{{{xmax:.0f}}}\n")

    print(f"wrote {args.out_dir}/copy_progress.dat ({len(pts)} points)")
    if mig is not None:
        print(f"  migration at t={mig:.3f}s; copy duration "
              f"{float(done.group(1)) - t0:.1f}s rc={done.group(2)}" if done
              else f"  migration at t={mig:.3f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
